import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function PrivacyPolicy() {
    return (
        <div  className="privacy-policy-page">
            <Header />
             <div className="page-header">
          <div className="container">
            <h1>Privacy Policy</h1>
          </div>
        </div>
            <div className="container large">
                <div className="privacy-policy-content">
                    <p>Last updated: December 07, 2023</p>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    <h2>Interpretation and Definitions                    </h2>
                    <h3>Interpretation</h3>
                    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h3>Definitions                    </h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="list">
                        <li>Account means a unique account created for You to access our Service or parts of our Service.                        </li>
                        <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                        </li>
<li>Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Skinny Tax Corporation , 6200 Hollywood Blvd, STE 1645, Los Angeles, CA 90028.
</li>
<li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
</li>
<li>Country refers to: California, United States
</li>
<li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
</li>
<li>Personal Data is any information that relates to an identified or identifiable individual.
</li>
<li>Service refers to the Website.
</li>
<li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
</li>
<li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.
</li>
<li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
</li>
<li>Website refers to SkinnyTax, accessible from   <a href="#">http://www.skinny.tax.etemps.info</a>
</li>
<li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
</li>
                    </ul>
                </div>
                <h2></h2>
            </div>
            <Footer />
        </div>
    );
}